name: DEVELOP

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x.x, 17.x.x, 18.x.x]
    
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: twitterclone
          POSTGRES_PASSWORD: twitteradmin
          POSTGRES_USER: twitteradmin
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      
    
    steps:
      - uses: action/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: action/setup@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test